### ISSUE TITLE
Test fail on chromedriver error

### ISSUE THREAD

**Issue by thomergil** [pako88/wdio-mocha-typescript#3]
```
$ npm install
[...]

$ npm run test:chromedriver                                                                                       <<<

> wdio-mocha-typescript@1.0.0 test:chromedriver /Users/thomer/tmp/nobackup/wdio-mocha-typescript
> npx wdio config/chromedriver.conf.js


Execution of 7 spec files started at 2020-07-09T13:31:53.960Z

Could not find chromedriver in default path:  /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver
Falling back to use global chromedriver bin
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver',
  path: '/Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver',
  spawnargs: [ '--port=9515', '--url-base=/' ]
}
[0-1] RUNNING in chrome - /test/specs/webdriver/the-internet/actions.ts
[0-1]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0] RUNNING in chrome - /test/specs/webdriver/basic.ts
[0-0]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-1] FAILED in chrome - /test/specs/webdriver/the-internet/actions.ts
[0-0] FAILED in chrome - /test/specs/webdriver/basic.ts
[0-2] RUNNING in chrome - /test/specs/webdriver/the-internet/chained-locator-with-multiple-elements.ts
[0-2]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-3] RUNNING in chrome - /test/specs/webdriver/the-internet/draganddrop.ts
[0-3]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-2] FAILED in chrome - /test/specs/webdriver/the-internet/chained-locator-with-multiple-elements.ts
[0-3] FAILED in chrome - /test/specs/webdriver/the-internet/draganddrop.ts
[0-4] RUNNING in chrome - /test/specs/webdriver/the-internet/dropdown.ts
[0-4]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-5] RUNNING in chrome - /test/specs/webdriver/the-internet/fileupload.ts
[0-5]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-4] FAILED in chrome - /test/specs/webdriver/the-internet/dropdown.ts
[0-5] FAILED in chrome - /test/specs/webdriver/the-internet/fileupload.ts
[0-6] RUNNING in chrome - /test/specs/webdriver/the-internet/iframe.ts
[0-6]  Error:  Failed to create session.
Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-6] FAILED in chrome - /test/specs/webdriver/the-internet/iframe.ts

Spec Files:	 0 passed, 7 failed, 7 total (100% completed) in 00:00:16

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdio-mocha-typescript@1.0.0 test:chromedriver: `npx wdio config/chromedriver.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdio-mocha-typescript@1.0.0 test:chromedriver script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomer/.npm/_logs/2020-07-09T13_32_11_056Z-debug.log```

**Comment by pako88** [comment]
do you had any error while executing `npm install` ?
chromedriver should be installed with following package: 
https://github.com/pako88/wdio-mocha-typescript/blob/master/package.json#L35

**Comment by thomergil** [comment]
Well, I probably did something dumb. I re-cloned the repo, ran `npm install` again, and now it works. So I probably did something stupid. My apologies. Closing this issue.

**Comment by thomergil** [comment]
So, I wasn't crazy after all. It appears that this problem relates to problems with how ChromeDriver gets installed. But after rerunning `npm install`, I get the errors above back. During `npm install` it says:

```
ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/q0/f4tncvcs2k7_v_skcsrsq78m0000gn/T/83.0.4103.39/chromedriver/chromedriver'.
Copying to target path /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver

> core-js@3.6.5 postinstall /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/core-js
```

Then running tests causes:

```
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[0-0] RUNNING in chrome - /test/specs/webdriver/thomer.ts
[0-0]  Error:  Failed to create session.
Make sure to connect to valid hostname:port or the port is not in use.
If you use a grid server
Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
See more https://www.w3.org/TR/webdriver/#capabilities
```

However, I believe this is unrelated to your code. It appears to be a ChromeDriver installation problem.

**Comment by thomergil** [comment]
Solved on macOs by `brew cask install chromedriver` and removing `chromedriver` from `package.json`

**Comment by pako88** [comment]
strange - i never had such issues with linux and windows - maybe it is macos related.  
but this has nothing to do with this project - so please open this bug in the chromedriver project:
https://github.com/giggio/node-chromedriver

closing this here, thanks for your understanding
